- name: create group IAM AWS
  hosts: localhost
  tasks:
          - name: create group
            iam:
                    iam_type: group
                    name: analistas
                    state: present


          - name: create group financeiro
            iam:
                    iam_type: group
                    name: financeiro
                    state: present


          - name: create user gabriel and add group analistas
            iam:
                    iam_type: user
                    name: gabriel
                    password: devops
                    state: present
                    access_key_state: create
                    groups: analistas



          - name: create user araujo and add group financeiro
            iam:
                    iam_type: user
                    name: araujo
                    password: devops
                    state: present
                    access_key_state: create
                    groups: financeiro



          - name: create policy group analistas
            iam_policy:
             iam_type: group
             iam_name: analistas
             policy_name: rules_analistas
             state: present
             policy_document: /etc/ansible/playbooks/analista.json


          - name: create policy group financeiro
            iam_policy:
             iam_type: group
             iam_name: financeiro
             policy_name: rules_financeiro
             state: present
             policy_document: /etc/ansible/playbooks/financeiro.json

